version: '3.3'
services:
  eTaskify:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '1010:3306'
    volumes:
      - my-db:/var/lib          /mysql
  adminer:
    image: dockette/adminer:full-php5
    ports:
      - '1928:9090'
volumes:
  my-db: